exports.toTrack = ['ο', 'η', 'το', 'τον', 'του', 'της', 'τους', 'τις', 'στο', 'στον', 'στη', 'στην', 'στους', 'στις', 'αν', 'και', 'κι', 'θα', 'τα', 'να', 'αν'];

exports.spamUrls = ['vimeo', 'meacolpa', 'inpost.gr', 'deals', 'thesout.gr', 'livestream', 'soccer', 'happydeals', 't-bet', 'pontarisma', 'foursquare', 'balleto.gr', 'ediagonismoi', 'christostriathlon', 'pblogs', 'xaros7', 'balla.com.cy', 'prasini', 'sentragoal', 'prasinanea', 'kingbet', 'pentelikonews', 'prognostika.net', 'olympia.gr', 'akous.gr', 'defence', 'tlife', 'mylady', 'google', 'amazon', 'tv', 'fm','england365','itunes', 'me-nu', 'newspistol', 'geziradyo', 'booker', 'diaforetiko', 'kidogarten', 'pokercity', 'eparousia', 'aggouria', 'twitpic', 'stoixima', 'wikipedia', 'networkedblogs', 'i-diadromi.gr', 'entertainment.in.gr','lawmediation', 'techcrunch', 'poiein', 'mycampus', 'olympiacos', 'blogspot', 'pistepseto', 'contra.gr', 'weheartit', 'cityportal', 'supernaturalgreece', 'milliyet', 'aek', 'radio', 'mpasket', 'betblog', 'twitter', 'rednews', '9gag', 'facebook', 'unfollow', 'q.gs', 'adf.ly', 'gkourou', 'pao', 'sport', 'youtube', 'apps', 'fplus.me', 'instagram', 'onit', 'feedburner', 'apoel', 'redplanet', 'dlvr.it', 'videomusicawards', 'omonoiag9', 'yellowfever', 'ticketshop', 'zdn', 'bno', 'indymedia', 'gavros', 'cretanpatriot', 'ractravel', 'stokokkino', 'twitlonger', 'dailymotion', 'apax-market', 'periodiko.net', 'kazani', 'betpartner', 'papaioannou', 'adiexodos', 'i-jukebox', 'toxwni', 'diorismos', 'winfarm', 'stardoll', 'istoselides', 'politisnews', 'axiaplus', 'epikaira', 'kathimerini', 'taglol', 'rthess', 'scoop', 'paraskhnio', 'capital', 'pathfinder', 'mousa', 'iatronet', 'euro2day', 'petitemaison', 'thessalonikicityguide', 'e-go', 'doriforikanea', 'naxos-news', 'news.gr', 'bestoflarissa', 'ow.ly', 'carpe-diem', 'express', 'redmania7', 'archive.avgi', 'alexandroupoli.net', 'hotot', 'gr.omg.yahoo.com', 'cosmote', 'vodafone', 'missbloom', 'kaltsa', 'cosmopoliti', 'onlycy', 'couponia', 'msfree', 'marymary', 'kerkida', 'neolaia', 'topseller', 'goalunited', 'atypos', 'cretadrive', 'queen', 'ictmax', 'flix', 'jackpotcitycasino', 'bestgift', 'enternity', '.jp', 'aggelies', 'k-tipos', 'nextlevelgroup', 'psixologikosfaros', 'pasgiannina', 'astrolife', 'scorebet', 'mycomputer', 'astynomia', 'tourist', 'gazzetta', 'i-guru', 'hit-channel', 'woop', 'trifiliworld', 'yupiii', 'palema', 'i-pet', 'protathlima', 'extend-graphics', 'game', 'transs', 'kutsompolia', 'patris', 'preveza'];

exports.titleSpam = ['&#;', '[φώτο]', '[ΦΩΤΟ]', '[φωτο]', '[φωτό]', '[βίντεο]', '[ΒΙΝΤΕΟ]', '[VID]', '[vid]', '[video]', '[VIDEO]', '(φώτο)', '(ΦΩΤΟ)', '(φωτο)', '(φωτό)', '(βίντεο)', '(ΒΙΝΤΕΟ)', '(VID)', '(vid)', '(video)', '(VIDEO)'];


//encoding problems: 'preveza', 'patris', 'politisnews', 'axiaplus', 'epikaira', 'kathimerini', rthess, 'capital', 'pathfinder', 'mousa', 'iatronet', 'euro2day', 'e-go', 'doriforikanea', 'naxos-news', 'news.gr', 'bestoflarissa', 'k-tipos', 'psixologikosfaros', 'protathlima'

//celebrity: 'omg.yahoo', 'cosmopoliti',' marymary', 'neolaia', 'queen', 'flix', 'yupiii', 'kutsompolia'

//sport: 'onlycy', 'msfree', 'kerkida', 'cretadrive', 'pasgiannina', 'scorebet', 'gazzetta', 'woop', 'trifiliworld', 'palema', 'protathlima'

//tech: , 'mycomputer', 'i-guru'